name: Checkout Code - CuddleBuddyPups

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  checkout_code:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
